name: Deploy Program

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 14

      - name: Read Firebase service account
        id: read-json
        run: echo "$FIREBASE_SECRETSERVICE" >> $GITHUB_ENV
        env:
            FIREBASE_SECRETSERVICE: ${{ secrets.FIREBASE_SECRETSERVICE }}

      - name: Read Firebase Url
        id: read-url
        run: echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" >> $GITHUB_ENV
        env:
            DATABASE_URL: ${{ secrets.DATABASE_URL }}

      - name: Install dependencies
        run: npm install

      - name: Deploy to Firebase
        run: 
          node server.js