name: Deploy Program

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 14

      - name: Read Firebase service account
        id: read-json
        run: echo "FIREBASE_SECRETSERVICE=${{ secrets.FIREBASE_SECRETSERVICE }}" >> $GITHUB_ENV
        env:
            FIREBASE_SECRETSERVICE: ${{ secrets.FIREBASE_SECRETSERVICE }}

      - name: Read Firebase Url
        id: read-url
        run: echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" >> $GITHUB_ENV
        env:
            DATABASE_URL: ${{ secrets.DATABASE_URL }}

      - name: Decode Firebase Service Account
        run: echo $FIREBASE_SECRETSERVICE | base64 --decode > serviceAccountKey.json

      - name: Install dependencies
        run: npm install

      - name: Debug Environment Variable 1 in Node.js
        run: node -e "console.log(process.env.FIREBASE_SECRETSERVICE)"

      - name: Debug Environment Variable 2 in Node.js
        run: node -e "console.log(process.env.DATABASE_URL)"

      - name: Install pm2
        run: npm install -g pm2
      
      - name: Deploy to Server
        run: 
            pm2 start server.js
    
      - name: Stop Server
        run: pm2 stop all
          